# Generated by Django 5.2.15 on 2026-06-19 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt_en', models.TextField()),
                ('excerpt_ar', models.TextField()),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField()),
                ('author', models.CharField(default='Dr. Karim Eltaher', max_length=120)),
                ('cover_image_url', models.URLField(blank=True)),
                ('read_time_minutes', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
