# Generated by Django 5.2.15 on 2026-06-20 15:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body_en',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
